"""knowledge/ 문서를 스캔해 references/INDEX.md 카탈로그를 생성한다.

이 스크립트는 `references/knowledge/<topic>/<file>.md` 트리를 순회하며 각 문서의
frontmatter(제한 문법만 지원 — PyYAML 등 외부 의존성 없음)와 본문을 읽어
DocMeta 목록을 만들고, 이를 표 형태의 INDEX.md로 렌더링한다.

- `governance/` 문서는 스캔 대상이 아니다 (knowledge/만).
- topic 아래 추가 중첩(`knowledge/<topic>/<sub>/<file>.md`)은 오류로 보고한다 —
  이것이 지식 트리가 시간이 지나도 깊어지지 않도록 막는 구조적 장치다.
- key(파일명)는 knowledge/ 전체에서 유일해야 한다.
- summary는 frontmatter의 유일한 필수 필드다.
- 문서 본문에 '## 적용 기준'과 '## 규칙' 레벨2 헤딩이 모두 있어야 성숙(draft=False)
  으로 판정한다. 헤딩이 아니라 문장 속에 같은 문구가 등장하는 것만으로는 성숙 처리하지
  않는다 — draft 문서는 판정 근거로 인용될 수 없다는 규칙이 이 판정에 달려 있다.
- 본문의 `[[key]]` 위키링크가 존재하지 않는 key를 가리키면 오류로 보고한다.

CLI로 직접 실행하면 이 스크립트 위치를 기준으로 `references/`를 찾아
`references/INDEX.md`를 덮어쓴다(오류가 있으면 stderr에 출력하고 exit 1).
"""

import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

WIKILINK_RE = re.compile(r"\[\[([^\[\]]+)\]\]")
META_LINE_RE = re.compile(r"^([A-Za-z0-9_-]+):\s*(.*)$")
MATURE_HEADINGS = ("## 적용 기준", "## 규칙")

GENERATED_HEADER = (
    "<!-- GENERATED by superdomain build_index.py — "
    "직접 수정 금지, 문서의 frontmatter·본문을 수정한 뒤 재실행할 것 -->"
)


@dataclass
class DocMeta:
    key: str            # 파일명(확장자 제외)
    topic: str           # 상위 디렉터리명
    summary: str
    read_when: list = field(default_factory=list)  # [str]
    draft: bool = True   # "## 적용 기준"과 "## 규칙" 헤딩이 모두 있어야 False


def _parse_meta_value(raw: str):
    """`값` 문자열 하나를 파싱한다. `[a, b]` 형태면 리스트로, 아니면 그대로 문자열로."""
    raw = raw.strip()
    if raw.startswith("[") and raw.endswith("]"):
        inner = raw[1:-1]
        return [item.strip() for item in inner.split(",") if item.strip()]
    return raw


def parse_frontmatter(text: str) -> tuple:
    """(meta: dict, body: str)를 반환한다. 제한 문법만 지원한다.

    첫 라인이 정확히 '---'일 때만 다음 '---' 라인까지를 frontmatter로 본다.
    frontmatter 블록 각 라인은 `키: 값` 형태여야 하며, 그렇지 않은 라인은 무시한다.
    값이 `[...]`로 감싸여 있으면 쉼표로 분리한 리스트로 파싱하고, 그 외 YAML 문법
    (중첩 맵, 따옴표 문자열, 멀티라인 등)은 지원하지 않는다.
    첫 라인이 '---'가 아니거나 닫는 '---'를 찾지 못하면 frontmatter 없음으로 보고
    전체 텍스트를 본문으로 반환한다.
    """
    lines = text.split("\n")
    if not lines or lines[0].strip() != "---":
        return {}, text

    closing = None
    for i in range(1, len(lines)):
        if lines[i].strip() == "---":
            closing = i
            break

    if closing is None:
        return {}, text

    meta = {}
    for line in lines[1:closing]:
        m = META_LINE_RE.match(line)
        if not m:
            continue  # '키: 값' 형태가 아닌 라인은 무시
        key, raw_value = m.group(1), m.group(2)
        meta[key] = _parse_meta_value(raw_value)

    body = "\n".join(lines[closing + 1:])
    return meta, body


def _is_mature(body: str) -> bool:
    """본문에 '## 적용 기준'과 '## 규칙' 레벨2 헤딩이 모두 라인 단위로 존재하는가.

    문구가 본문 어딘가(문장, 레벨3 헤딩 등)에 등장하는 것만으로는 충족되지 않는다 —
    반드시 해당 라인 전체가 정확히 그 헤딩이어야 한다.
    """
    heading_lines = {line.strip() for line in body.split("\n")}
    return all(heading in heading_lines for heading in MATURE_HEADINGS)


def scan_knowledge(references_dir) -> tuple:
    """references_dir/knowledge/<topic>/<file>.md 트리를 스캔한다.

    반환: ([DocMeta], [오류 문자열]). 오류 문자열은 모두 사람이 읽을 한국어이며,
    문제가 된 파일의 경로를 포함해 사람이 바로 조치할 수 있게 한다.
    """
    references_dir = Path(references_dir)
    knowledge_dir = references_dir / "knowledge"

    docs = []
    errors = []

    if not knowledge_dir.is_dir():
        return docs, errors

    seen_keys = {}     # key -> 처음 발견된 파일의 상대경로(중복 오류 메시지용)
    all_keys = set()   # 위키링크 대상 존재 검증용 — knowledge/ 안에 실재하는 모든 key
    link_refs = []      # (참조원 상대경로, 참조 대상 key)

    topic_dirs = sorted(
        p for p in knowledge_dir.iterdir()
        if p.is_dir() and not p.name.startswith(".")
    )

    for topic_dir in topic_dirs:
        topic = topic_dir.name
        for entry in sorted(topic_dir.rglob("*.md")):
            rel = entry.relative_to(references_dir).as_posix()
            depth_rel = entry.relative_to(topic_dir)

            if len(depth_rel.parts) > 1:
                errors.append(
                    f"중첩된 디렉터리: {rel} — knowledge/<topic>/<file>.md 형식만 "
                    f"허용됩니다(topic 아래 추가 중첩 금지)."
                )
                continue

            if entry.name.startswith("_"):
                continue  # 밑줄 접두 파일은 색인 대상에서 제외(초안 스크래치용)

            key = entry.stem
            text = entry.read_text(encoding="utf-8")
            meta, body = parse_frontmatter(text)

            all_keys.add(key)

            for m in WIKILINK_RE.finditer(body):
                link_refs.append((rel, m.group(1).strip()))

            if key in seen_keys:
                errors.append(f"중복된 key: '{key}' ({seen_keys[key]} / {rel})")
                continue
            seen_keys[key] = rel

            summary = meta.get("summary")
            if not summary:
                errors.append(f"{rel}: summary 필드가 없습니다(frontmatter의 유일한 필수 필드).")
                continue

            docs.append(DocMeta(
                key=key,
                topic=topic,
                summary=summary,
                read_when=meta.get("read_when") or [],
                draft=not _is_mature(body),
            ))

    # topic 디렉터리 없이 knowledge/ 바로 아래 놓인 파일 — 조용히 누락시키지 않고 오류로 보고
    for entry in sorted(knowledge_dir.glob("*.md")):
        rel = entry.relative_to(references_dir).as_posix()
        errors.append(
            f"주제 디렉터리 없음: {rel} — knowledge/<topic>/<file>.md 형식이어야 합니다."
        )

    for rel, target in link_refs:
        if target not in all_keys:
            errors.append(f"{rel}: 존재하지 않는 문서를 참조합니다 [[{target}]].")

    return docs, errors


def _fmt_list(items: list) -> str:
    return ", ".join(items)


def _escape_cell(value: str) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ")


def render_index(docs: list) -> str:
    """DocMeta 목록을 INDEX.md 전문(생성 헤더 포함)으로 렌더링한다. key로 정렬한다."""
    rows = sorted(docs, key=lambda d: d.key)

    lines = [
        GENERATED_HEADER,
        "# references INDEX",
        "",
        "| key | topic | summary | read_when | draft |",
        "|---|---|---|---|---|",
    ]
    for d in rows:
        cells = [
            d.key,
            d.topic,
            d.summary,
            _fmt_list(d.read_when),
            "draft" if d.draft else "",
        ]
        lines.append("| " + " | ".join(_escape_cell(c) for c in cells) + " |")

    return "\n".join(lines) + "\n"


def main() -> int:
    references_dir = Path(__file__).resolve().parent.parent / "references"
    docs, errors = scan_knowledge(references_dir)

    if errors:
        for e in errors:
            print(e, file=sys.stderr)
        return 1

    index_path = references_dir / "INDEX.md"
    index_path.write_text(render_index(docs), encoding="utf-8")
    print(f"OK: {index_path} 생성 완료 ({len(docs)}개 문서)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
