#!/usr/bin/env bash
# SessionStart 훅: cwd에서 git 루트까지 상향 탐색하며 docs/superdomain/summary.md를
# 찾아 그대로 출력한다(파싱하지 않는다). 없으면 조용히 종료한다.
# 다만 탐색 중 옛 배치(0.2.x — docs/domain-summary.md, 마커 있는 루트 DOMAIN.md)를 봤으면
# 이행을 안내하는 한 줄만 출력한다. 그 요약은 주입하지 않는다 — 스크립트가 옛 배치에서
# exit 2로 멈추므로, 옛 요약을 상시 규칙처럼 싣는 것은 거짓이 된다.
# docs/domain-summary.md는 0.2.x가 생성한 파일일 때만 옛 배치 흔적으로 본다 — 팀이 같은
# 경로에 직접 쓴 문서까지 옛 배치로 오인하지 않도록, 0.2.x의 생성 헤더(GENERATED by
# superdomain)가 있는지 확인한다.
set -euo pipefail
dir="$(pwd)"
legacy=""
while :; do
  if [ -f "$dir/docs/superdomain/summary.md" ]; then
    cat "$dir/docs/superdomain/summary.md" 2>/dev/null || true
    exit 0
  fi
  if [ -z "$legacy" ] && grep -qs 'GENERATED by superdomain' "$dir/docs/domain-summary.md"; then
    legacy="$dir"
  fi
  # docs/superdomain/DOMAIN.md는 새 선언이다 — 마커가 같으므로 탐색이 그 디렉터리를 지날 때는
  # 옛 루트 선언으로 보지 않는다.
  case "$dir" in
    */docs/superdomain) ;;
    *)
      if [ -z "$legacy" ] && grep -qs 'superdomain:template' "$dir/DOMAIN.md"; then
        legacy="$dir"
      fi
      ;;
  esac
  # git 루트(일반 저장소 디렉터리 또는 worktree 파일) 또는 파일시스템 루트에 도달하면 중단
  if [ -e "$dir/.git" ] || [ "$dir" = "/" ]; then
    break
  fi
  dir="$(dirname "$dir")"
done
if [ -n "$legacy" ]; then
  echo "[superdomain] 이 프로젝트는 옛 배치(0.2.x)입니다 — 스크립트가 exit 2로 멈춥니다. 이행 절차: ${CLAUDE_PLUGIN_ROOT:-<superdomain 플러그인>}/CHANGELOG.md 0.3.0"
fi
exit 0
