import shutil
import sys
import unittest
import tempfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "scripts"))
from build_index import parse_frontmatter, scan_knowledge, render_index

DOC_OK = """---
summary: 애그리거트 경계 설정 기준
read_when: [review, apply]
---

## 개념
...

## 적용 기준
- 체크리스트

## 규칙
- tactical.agg-boundary
"""

DOC_DRAFT = """---
summary: 초안 문서
---
자유 형식 메모. [[aggregates]] 참조.
"""


class TestFrontmatter(unittest.TestCase):
    def test_limited_syntax(self):
        meta, body = parse_frontmatter(DOC_OK)
        self.assertEqual(meta["summary"], "애그리거트 경계 설정 기준")
        self.assertEqual(meta["read_when"], ["review", "apply"])
        self.assertTrue(body.startswith("\n## 개념"))

    def test_missing_frontmatter(self):
        meta, body = parse_frontmatter("본문만 있음")
        self.assertEqual(meta, {})

    def test_body_lookalike_line_not_parsed_as_frontmatter(self):
        # 닫는 '---' 이후 본문에 '키: 값' 모양 라인이 있어도 frontmatter로 오인하지 않는다.
        text = "---\nsummary: 정상\n---\n\n주의: 이 줄은 본문이다\n"
        meta, body = parse_frontmatter(text)
        self.assertEqual(meta, {"summary": "정상"})
        self.assertNotIn("주의", meta)
        self.assertIn("주의: 이 줄은 본문이다", body)


class TestScan(unittest.TestCase):
    def setUp(self):
        self._tmp_dirs = []

    def tearDown(self):
        for d in self._tmp_dirs:
            shutil.rmtree(d, ignore_errors=True)

    def _make(self, files):  # {상대경로: 내용} → 임시 references/ 디렉터리
        d = Path(tempfile.mkdtemp(dir=Path(__file__).resolve().parent))
        self._tmp_dirs.append(d)
        for rel, content in files.items():
            p = d / "knowledge" / rel
            p.parent.mkdir(parents=True, exist_ok=True)
            p.write_text(content, encoding="utf-8")
        return d

    def test_draft_detection_and_topic(self):
        d = self._make({"tactical/aggregates.md": DOC_OK, "tactical/notes.md": DOC_DRAFT})
        docs, errors = scan_knowledge(d)
        self.assertEqual(errors, [])
        by_key = {x.key: x for x in docs}
        self.assertFalse(by_key["aggregates"].draft)
        self.assertTrue(by_key["notes"].draft)
        self.assertEqual(by_key["notes"].topic, "tactical")

    def test_missing_summary_is_error(self):
        d = self._make({"tactical/bad.md": "---\nread_when: [review]\n---\n본문"})
        docs, errors = scan_knowledge(d)
        self.assertTrue(any("summary" in e and "bad" in e for e in errors))

    def test_nested_topic_rejected(self):
        d = self._make({"tactical/deep/x.md": DOC_DRAFT})
        docs, errors = scan_knowledge(d)
        self.assertTrue(any("중첩" in e for e in errors))

    def test_duplicate_key_rejected(self):
        d = self._make({"tactical/same.md": DOC_OK, "patterns/same.md": DOC_OK})
        docs, errors = scan_knowledge(d)
        self.assertTrue(any("중복" in e for e in errors))

    def test_broken_wikilink_rejected(self):
        d = self._make({"tactical/notes.md": DOC_DRAFT})  # [[aggregates]] 참조하지만 부재
        docs, errors = scan_knowledge(d)
        self.assertTrue(any("aggregates" in e for e in errors))

    def test_stray_file_at_knowledge_root_rejected(self):
        # topic 디렉터리 없이 knowledge/ 바로 아래 놓인 파일도 오류로 보고해야 한다
        # (조용히 무시되면 문서가 INDEX에서 소리 없이 누락된다).
        d = self._make({})
        (d / "knowledge").mkdir(parents=True, exist_ok=True)
        (d / "knowledge" / "x.md").write_text(DOC_DRAFT, encoding="utf-8")
        docs, errors = scan_knowledge(d)
        self.assertTrue(any("x.md" in e for e in errors))
        self.assertEqual(docs, [])

    def test_draft_detection_anchored_to_heading_not_substring(self):
        # '## 규칙'은 진짜 레벨2 헤딩으로 존재하지만 '적용 기준'은 레벨3 헤딩
        # ('### 적용 기준 상세')으로만 등장한다. 문자열 포함 검사라면 '## 적용 기준'이
        # '### 적용 기준 상세' 안의 부분 문자열이라 성숙 처리해버리는 함정이 있다 —
        # 라인 단위 정확 매치라야 이 함정을 피해 draft=True를 유지한다.
        sneaky = """---
summary: 레벨3 헤딩 위장 문서
---

## 규칙
- 진짜 규칙 헤딩(레벨2, 정확)

### 적용 기준 상세
레벨3 헤딩이므로 성숙 조건을 충족하면 안 된다.
"""
        d = self._make({"tactical/sneaky.md": sneaky})
        docs, errors = scan_knowledge(d)
        self.assertEqual(errors, [])
        self.assertTrue(docs[0].draft)

    def test_wikilink_to_existing_doc_in_other_topic_not_rejected(self):
        d = self._make({"tactical/aggregates.md": DOC_OK, "patterns/notes.md": DOC_DRAFT})
        docs, errors = scan_knowledge(d)
        self.assertEqual(errors, [])


class TestRenderIndex(unittest.TestCase):
    def test_header_present_and_empty_body_valid(self):
        out = render_index([])
        self.assertIn(
            "<!-- GENERATED by superarchitect build_index.py — "
            "직접 수정 금지, 문서의 frontmatter·본문을 수정한 뒤 재실행할 것 -->",
            out,
        )
        self.assertIn("| key | topic | summary | read_when | draft |", out)

    def test_rows_sorted_by_key(self):
        from build_index import DocMeta
        docs = [
            DocMeta(key="zeta", topic="tactical", summary="z", read_when=[], draft=False),
            DocMeta(key="alpha", topic="tactical", summary="a", read_when=["review"], draft=True),
        ]
        out = render_index(docs)
        self.assertLess(out.index("| alpha "), out.index("| zeta "))

    def test_draft_flag_rendered(self):
        # 표 헤더 자체에 "draft"라는 글자가 들어있으므로(`| ... | draft |` 컬럼명),
        # `assertIn("draft", out)`처럼 렌더링 결과 전체를 상대로 단언하면 셀 렌더링
        # 로직이 완전히 망가지거나 문서가 0개여도 통과해버린다(헤더만으로 충족).
        # 반드시 해당 문서의 행 전체 모양을 단언하고, draft=False 문서는 셀이
        # 비어 있는지도 함께 확인해야 판별력이 생긴다.
        from build_index import DocMeta
        docs = [
            DocMeta(key="a", topic="t", summary="s", read_when=[], draft=True),
            DocMeta(key="b", topic="t", summary="s", read_when=[], draft=False),
        ]
        out = render_index(docs)
        self.assertIn("| a | t | s |  | draft |", out)
        self.assertIn("| b | t | s |  |  |", out)


if __name__ == "__main__":
    unittest.main()
